"""v1.0.0 — TodoMiddleware: let the LLM write its own plan.

v0.6.0-v0.9.0 had hardcoded plans (the user wrote a `Plan` object
ahead of time). v1.0.0 lets the LLM DYNAMICALLY generate the plan
via a `todo_update` tool call, mirroring DeerFlow's TodoMiddleware.

The flow:

  1. HOOK_PLAN_START fires (with whatever plan the user provided)
  2. The middleware exposes a `todo_update` tool to the LLM
  3. The LLM makes a `todo_update(steps=[...])` tool call
  4. The middleware (a) records the new plan in ctx.shared['todo_plan']
     and (b) tags ctx with a HALT-after-this-iteration directive so
     the calling plan_execute loop can swap the plan

The middleware itself doesn't call the LLM — that's the plan_execute
loop's job. We just:
- Provide the tool spec on demand (via `get_todo_tool_spec()`)
- Observe the tool call (via `on_tool_call(name, arguments)`)
- Expose the resulting plan via `ctx.shared['todo_plan']`

The plan_execute loop must:
1. Pass `todo_mw.get_todo_tool_spec()` into its LLM call
2. After the LLM call, call `todo_mw.on_tool_call(name, args)` for any
   tool calls in the response
3. If `ctx.shared.get('todo_plan')` is now set, use it as the plan

This split keeps the middleware framework-agnostic — it doesn't
depend on the specific LLM client.

Why this matters (Qian control theory):

- 早纠偏: a human-written plan often misses steps the LLM would
  notice ("oh, to do X I also need to do Y first"). Letting the LLM
  extend the plan at the start catches this BEFORE we start executing.
- 可控性: the user can see the LLM's plan in the scratchpad/logs
  before any side effects happen.
- 稳定性: the plan is committed ONCE, then executed. No mid-run
  plan mutation (which would break the executor's expectations).
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any

from .middleware import (
    HOOK_PLAN_END,
    HOOK_PLAN_START,
    HOOK_STEP_END,
    HookContext,
    Middleware,
)

logger = logging.getLogger(__name__)


# --------------------------------------------------------------------------- #
# Todo step data
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class TodoStep:
    """One step in the LLM's dynamic plan."""
    name: str
    action: str
    status: str = "pending"               # "pending" | "in_progress" | "done" | "skipped"
    notes: str = ""


@dataclass
class TodoPlan:
    """A full dynamic plan generated by the LLM."""
    goal: str
    steps: list[TodoStep] = field(default_factory=list)
    created_at: float = 0.0

    def names(self) -> list[str]:
        return [s.name for s in self.steps]

    def to_dict(self) -> dict[str, Any]:
        return {
            "goal": self.goal,
            "steps": [{"name": s.name, "action": s.action,
                       "status": s.status, "notes": s.notes}
                      for s in self.steps],
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "TodoPlan":
        return cls(
            goal=d.get("goal", ""),
            steps=[TodoStep(
                name=s.get("name", ""),
                action=s.get("action", ""),
                status=s.get("status", "pending"),
                notes=s.get("notes", ""),
            ) for s in d.get("steps", [])],
        )


# --------------------------------------------------------------------------- #
# TodoMiddleware
# --------------------------------------------------------------------------- #


class TodoMiddleware:
    """Let the LLM write its own plan via a `todo_update` tool.

    Usage:
        todo_mw = TodoMiddleware()
        chain = MiddlewareChain([todo_mw, ...])

        # In your plan_execute loop, when calling the LLM:
        response = client.chat(messages, tools=todo_mw.tool_specs())

        # Process any tool calls in the response:
        for call in response.tool_calls:
            todo_mw.on_tool_call(call.name, call.arguments, ctx)

        # After the call, check if the LLM has a new plan:
        if todo_mw.has_plan() and not getattr(plan, "_locked", False):
            plan = todo_mw.build_plan_for(goal)
    """

    name = "todo"

    def __init__(self, *, min_steps: int = 1, max_steps: int = 20) -> None:
        # Tunables
        self.min_steps = min_steps
        self.max_steps = max_steps
        # State: the current plan (None until LLM sets it)
        self._plan: TodoPlan | None = None

    # ----- middleware protocol ------------------------------------------

    def __call__(self, ctx: HookContext) -> None:
        if ctx.hook == HOOK_PLAN_START:
            # Reset for a new run
            self._plan = None
            logger.debug("[todo] plan_start — todo list reset")
        elif ctx.hook == HOOK_PLAN_END:
            if self._plan is not None:
                logger.info("[todo] plan_end — final plan had %d step(s)",
                            len(self._plan.steps))

    # ----- tool spec (call from your plan_execute loop) ----------------

    def tool_specs(self) -> list[dict[str, Any]]:
        """Return the OpenAI-format tool specs the LLM should see.

        Exposes a single `todo_update` tool. The LLM calls it with
        a list of steps; the middleware validates and stores.
        """
        return [{
            "type": "function",
            "function": {
                "name": "todo_update",
                "description": (
                    "Replace your plan for this task with a fresh, "
                    "ordered list of steps. Use this BEFORE doing any "
                    "other work, so the user can see what you intend "
                    "to do. Each step has a short name and a one-line "
                    "action description."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "steps": {
                            "type": "array",
                            "minItems": self.min_steps,
                            "maxItems": self.max_steps,
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "description": "Short step name (e.g. 'load_data')",
                                    },
                                    "action": {
                                        "type": "string",
                                        "description": "What to do in this step",
                                    },
                                },
                                "required": ["name", "action"],
                            },
                        },
                    },
                    "required": ["steps"],
                },
            },
        }]

    # ----- tool call handler (call from your plan_execute loop) --------

    def on_tool_call(self, name: str, arguments: dict[str, Any], ctx: HookContext) -> str:
        """Handle a tool call from the LLM. Returns a JSON string for
        the tool result message (the loop will pass this back to the LLM).
        """
        if name != "todo_update":
            return self._err(f"unknown tool: {name!r}")

        try:
            steps = arguments.get("steps", [])
            if not isinstance(steps, list):
                return self._err("steps must be a list")
            if len(steps) < self.min_steps:
                return self._err(f"need at least {self.min_steps} step(s)")
            if len(steps) > self.max_steps:
                return self._err(f"too many steps (max {self.max_steps})")

            todo_steps: list[TodoStep] = []
            seen_names: set[str] = set()
            for i, s in enumerate(steps):
                if not isinstance(s, dict):
                    return self._err(f"step[{i}] must be a dict")
                step_name = s.get("name", "")
                action = s.get("action", "")
                if not isinstance(step_name, str) or not step_name:
                    return self._err(f"step[{i}].name must be a non-empty string")
                if not isinstance(action, str) or not action:
                    return self._err(f"step[{i}].action must be a non-empty string")
                if step_name in seen_names:
                    return self._err(f"duplicate step name: {step_name!r}")
                seen_names.add(step_name)
                todo_steps.append(TodoStep(name=step_name, action=action))

            self._plan = TodoPlan(goal=ctx.goal, steps=todo_steps)
            ctx.shared["todo_plan"] = self._plan
            # The plan is now set; the loop should call has_plan() and
            # rebuild the Plan if so. We emit a LOG directive so
            # downstream middleware can observe the plan change.
            from .middleware import Directive
            ctx.directives.append(Directive(
                kind="LOG",
                detail=f"todo plan set with {len(todo_steps)} step(s)",
            ))
            return json.dumps({
                "ok": True,
                "step_count": len(todo_steps),
                "names": todo_steps[0].name and [s.name for s in todo_steps],
            })
        except Exception as e:  # noqa: BLE001
            return self._err(f"{type(e).__name__}: {e}")

    @staticmethod
    def _err(msg: str) -> str:
        return json.dumps({"ok": False, "error": msg})

    # ----- accessors for the plan_execute loop --------------------------

    def has_plan(self) -> bool:
        return self._plan is not None

    def get_plan(self) -> TodoPlan | None:
        return self._plan

    def reset(self) -> None:
        """Discard the current plan. Use between runs."""
        self._plan = None


__all__ = ["TodoMiddleware", "TodoStep", "TodoPlan"]
