"""L4 — Insight memory layer.

Insights are cross-session meta-patterns. Whereas L1 atoms are
single facts and L2 scenarios are per-session aggregations, L4
insights span the whole memory history and surface repeated patterns
(e.g. "user always asks for Mermaid diagrams", "user prefers running
in tmux with 3 panes").

L4 lives in SQLite (``memory_insights``) plus an aggregated
``~/.madcop/memory/insights.md`` rollup for human inspection.
"""

from __future__ import annotations

import json
import sqlite3
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from .store import MemoryStore


@dataclass
class Insight:
    """A cross-session pattern discovered from L1/L2/L3 aggregation."""

    id: str
    title: str
    description: str
    evidence_atom_ids: list[str] = field(default_factory=list)
    evidence_scenario_ids: list[str] = field(default_factory=list)
    evidence_persona_keys: list[str] = field(default_factory=list)
    confidence: float = 0.0
    occurrences: int = 1
    first_seen: float = field(default_factory=time.time)
    last_seen: float = field(default_factory=time.time)
    tags: list[str] = field(default_factory=list)


class InsightMemory:
    """L4 cross-session insight layer."""

    def __init__(self, store: MemoryStore) -> None:
        self.store = store
        self.insights_path = store.path.parent / "memory" / "insights.md"
        self.insights_path.parent.mkdir(parents=True, exist_ok=True)
        if not self.insights_path.exists():
            self.insights_path.write_text(
                "# Cross-Session Insights\n\n"
                "_Auto-generated by the InsightBuilder. Each insight is a "
                "pattern observed across multiple L1/L2/L3 entries._\n\n",
                encoding="utf-8",
            )
        self._ensure_table()

    def _conn(self) -> sqlite3.Connection:
        return sqlite3.connect(str(self.store.path))

    def _ensure_table(self) -> None:
        conn = self._conn()
        try:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS memory_insights (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    evidence_atom_ids TEXT NOT NULL DEFAULT '[]',
                    evidence_scenario_ids TEXT NOT NULL DEFAULT '[]',
                    evidence_persona_keys TEXT NOT NULL DEFAULT '[]',
                    confidence REAL NOT NULL DEFAULT 0.0,
                    occurrences INTEGER NOT NULL DEFAULT 1,
                    first_seen REAL NOT NULL,
                    last_seen REAL NOT NULL,
                    tags TEXT NOT NULL DEFAULT '[]'
                )
                """
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_insights_confidence "
                "ON memory_insights(confidence DESC)"
            )
            conn.commit()
        finally:
            conn.close()

    def upsert(self, insight: Insight) -> None:
        insight.last_seen = time.time()
        conn = self._conn()
        try:
            existing = conn.execute(
                "SELECT id, occurrences FROM memory_insights WHERE id = ?",
                (insight.id,),
            ).fetchone()
            if existing:
                conn.execute(
                    """UPDATE memory_insights SET
                       title = ?, description = ?,
                       evidence_atom_ids = ?, evidence_scenario_ids = ?,
                       evidence_persona_keys = ?,
                       confidence = ?, occurrences = ?,
                       last_seen = ?, tags = ?
                       WHERE id = ?""",
                    (
                        insight.title, insight.description,
                        json.dumps(insight.evidence_atom_ids),
                        json.dumps(insight.evidence_scenario_ids),
                        json.dumps(insight.evidence_persona_keys),
                        insight.confidence, int(existing["occurrences"]) + 1,
                        insight.last_seen,
                        json.dumps(insight.tags),
                        insight.id,
                    ),
                )
            else:
                conn.execute(
                    """INSERT INTO memory_insights
                       (id, title, description, evidence_atom_ids,
                        evidence_scenario_ids, evidence_persona_keys,
                        confidence, occurrences, first_seen, last_seen, tags)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                    (
                        insight.id, insight.title, insight.description,
                        json.dumps(insight.evidence_atom_ids),
                        json.dumps(insight.evidence_scenario_ids),
                        json.dumps(insight.evidence_persona_keys),
                        insight.confidence, insight.occurrences,
                        insight.first_seen, insight.last_seen,
                        json.dumps(insight.tags),
                    ),
                )
            conn.commit()
        finally:
            conn.close()
        self._rewrite_markdown()

    def list(self, min_confidence: float = 0.0, limit: int = 100) -> list[Insight]:
        conn = self._conn()
        try:
            rows = conn.execute(
                """SELECT * FROM memory_insights
                   WHERE confidence >= ?
                   ORDER BY confidence DESC, occurrences DESC, last_seen DESC
                   LIMIT ?""",
                (min_confidence, limit),
            ).fetchall()
        finally:
            conn.close()
        return [self._row_to_insight(r) for r in rows]

    def to_public_dict(self) -> dict[str, Any]:
        return {
            "path": str(self.insights_path),
            "insights": [
                {
                    "id": i.id, "title": i.title, "description": i.description,
                    "confidence": i.confidence, "occurrences": i.occurrences,
                    "first_seen": i.first_seen, "last_seen": i.last_seen,
                    "tags": i.tags,
                }
                for i in self.list()
            ],
            "raw": self.insights_path.read_text(encoding="utf-8"),
        }

    # -- internal ------------------------------------------------------- #

    def _rewrite_markdown(self) -> None:
        items = self.list()
        lines = [
            "# Cross-Session Insights",
            "",
            "_Auto-generated by the InsightBuilder. Each insight is a "
            "pattern observed across multiple L1/L2/L3 entries._",
            "",
        ]
        for i in items:
            lines.append(f"## {i.title}")
            lines.append("")
            lines.append(f"_{i.description}_")
            lines.append("")
            lines.append(f"- **Confidence:** {i.confidence:.2f}")
            lines.append(f"- **Occurrences:** {i.occurrences}")
            if i.tags:
                lines.append(f"- **Tags:** {', '.join(i.tags)}")
            lines.append("")
        self.insights_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def _row_to_insight(self, row: sqlite3.Row) -> Insight:
        def _load(name: str) -> list[str]:
            try:
                v = json.loads(row[name] or "[]")
                return list(v) if isinstance(v, list) else []
            except Exception:
                return []
        return Insight(
            id=row["id"],
            title=row["title"],
            description=row["description"],
            evidence_atom_ids=_load("evidence_atom_ids"),
            evidence_scenario_ids=_load("evidence_scenario_ids"),
            evidence_persona_keys=_load("evidence_persona_keys"),
            confidence=float(row["confidence"]),
            occurrences=int(row["occurrences"]),
            first_seen=float(row["first_seen"]),
            last_seen=float(row["last_seen"]),
            tags=_load("tags"),
        )
