import http from 'node:http';
import WS from 'ws';
process.stdout.write('start\n');
const r1 = await fetch('http://127.0.0.1:9444/json/list');
const targets = await r1.json();
process.stdout.write(`targets: ${targets.length}\n`);
const page = targets.find(t => t.type === 'page' && t.url.startsWith('file://'));
process.stdout.write(`page: ${page ? page.url : 'none'}\n`);
const ws = new WS(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
ws.on('message', (m) => { try { const msg = JSON.parse(m.data.toString()); if (msg.id && pending.has(msg.id)) { pending.get(msg.id)(msg); pending.delete(msg.id); } } catch (e) { process.stdout.write('err: ' + e.message + '\n'); } });
ws.on('error', (e) => process.stdout.write(`ws error: ${e.message}\n`));
await new Promise(r => ws.once('open', r));
process.stdout.write('ws open\n');
const send = (method, params) => new Promise(r => { const _id = ++id; pending.set(_id, r); ws.send(JSON.stringify({id: _id, method, params})); });
const r = await send('Runtime.evaluate', { expression: '1+1' });
process.stdout.write(`1+1: ${JSON.stringify(r)}\n`);
ws.close();
process.stdout.write('done\n');
